services:
  backend:
    image: ghcr.io/cristian-yw/weekly10:latest
    volumes:
      - ./.env:/app/.env
    depends_on:
      - db
      - redis
    networks:
      - tickitz-net   # agar poster bisa diakses
    ports:
    - "8080:8080"  # expose backend ke host

  frontend:
    image: ghcr.io/cristian-yw/c_tickitz:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/sites-available/app.conf:/etc/nginx/conf.d/app.conf:ro
    networks:
      - tickitz-net
    depends_on:
      - backend
  redis:
    image: redis:8.2-alpine
    volumes:
      - redis-tickitz:/data
    networks:
      - tickitz-net
    ports:
      - 6370:6379

  db:
    image: postgres:18-alpine3.22
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5423:5432"
    networks:
      - tickitz-net

networks:
  tickitz-net:

volumes:
  db_data:
  redis-tickitz:
