services:
  backend:
    image: ghcr.io/cristian-yw/weekly10:latest
    volumes:
      - ./.env:/app/.env
    depends_on:
      - db
      - redis
    networks:
      - tickitz-net   # agar poster bisa diakses
    ports:
    - "8080:8080"  # expose backend ke host

migrate:
  image: migrate/migrate
  volumes:
    - ./db/migrations:/migrations
  command:
    - "-path=/migrations"
    - "-database=postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}?sslmode=disable"
    - "up"  # ← This runs ALL pending migrations
  depends_on:
    db:
      condition: service_healthy
  networks:
    - tickitz-net
  restart: on-failure

  frontend:
    image: ghcr.io/cristian-yw/c_tickitz:latest
    ports:
      - "80:80"
    networks:
      - tickitz-net
    depends_on:
      - backend
  redis:
    image: redis:8.2-alpine
    volumes:
      - redis-tickitz:/data
    networks:
      - tickitz-net
    ports:
      - 6370:6379

  db:
    image: postgres:18-alpine3.22
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5423:5432"
    networks:
      - tickitz-net

networks:
  tickitz-net:

volumes:
  db_data:
  redis-tickitz:
